//
//  TyDyListSceneInteractor.swift
//  TyDy
//
//  Created by Mac on 25/01/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TyDyListSceneBusinessLogic {
    func addItem(request: TyDyListScene.AddItem.Request)
    func saveItem(request: TyDyListScene.SaveNewItem.Request)
    func loadData(request: TyDyListScene.LoadData.Request)
    func updateData(request: TyDyListScene.UpdateData.Request)
    func saveData(request: TyDyListScene.SaveData.Request)
}

protocol TyDyListSceneDataStore {
    var itemArray: [TyDyItem]? { get set }
}

class TyDyListSceneInteractor: TyDyListSceneBusinessLogic, TyDyListSceneDataStore {
    
    var presenter: TyDyListScenePresentationLogic?
    var worker: TyDyListSceneWorker?
    var itemArray: [TyDyItem]? = [TyDyItem]()
    
  
  // MARK: Do something
  
    func addItem(request: TyDyListScene.AddItem.Request) {
        let response = TyDyListScene.AddItem.Response()
        self.presenter?.presentAddItem(response: response)
    }
    
    func saveItem(request: TyDyListScene.SaveNewItem.Request) {
        self.itemArray?.append(request.item)
        self.worker?.saveData(data: self.itemArray)
        
        let response = TyDyListScene.SaveNewItem.Response()
        self.presenter?.presentSaveItem(response: response)
    }
    
    func loadData(request: TyDyListScene.LoadData.Request) {
        if let loadedArray = self.worker?.loadData() {
            self.itemArray = loadedArray
        }

        let response = TyDyListScene.LoadData.Response()
        self.presenter?.presentLoadData(response: response)
    }
    
    func updateData(request: TyDyListScene.UpdateData.Request) {
        let response = TyDyListScene.UpdateData.Response()
        self.presenter?.presentUpdateData(response: response)
    }
    
    func saveData(request: TyDyListScene.SaveData.Request) {
        self.worker?.saveData(data: self.itemArray)

        let response = TyDyListScene.SaveData.Response()
        self.presenter?.presentSaveData(response: response)
    }
    
}
