//
//  TyDyListSceneInteractor.swift
//  TyDy
//
//  Created by Mac on 25/01/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TyDyListSceneBusinessLogic {
    func addItem(request: TyDyListScene.AddItem.Request)
}

protocol TyDyListSceneDataStore
{
  //var name: String { get set }
}

class TyDyListSceneInteractor: TyDyListSceneBusinessLogic, TyDyListSceneDataStore
{
  var presenter: TyDyListScenePresentationLogic?
  var worker: TyDyListSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func addItem(request: TyDyListScene.AddItem.Request) {
        let response = TyDyListScene.AddItem.Response()
        self.presenter?.presentAddItem(response: response)
    }
    
}
