//
//  TyDyListScenePresenter.swift
//  TyDy
//
//  Created by Mac on 25/01/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TyDyListScenePresentationLogic
{
  func presentSomething(response: TyDyListScene.Something.Response)
}

class TyDyListScenePresenter: TyDyListScenePresentationLogic
{
  weak var viewController: TyDyListSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TyDyListScene.Something.Response)
  {
    let viewModel = TyDyListScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
