//
//  TyDyListScenePresenter.swift
//  TyDy
//
//  Created by Mac on 25/01/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TyDyListScenePresentationLogic {
    func presentAddItem(response: TyDyListScene.AddItem.Response)
    func presentSaveItem(response: TyDyListScene.SaveNewItem.Response)
    func presentLoadData(response: TyDyListScene.LoadData.Response)
    func presentUpdateData(response: TyDyListScene.UpdateData.Response)
    func presentSaveData(response: TyDyListScene.SaveData.Response)
}

class TyDyListScenePresenter: TyDyListScenePresentationLogic {
    weak var viewController: TyDyListSceneDisplayLogic?
  
    // MARK: Do something
  
    func presentAddItem(response: TyDyListScene.AddItem.Response) {
        let viewModel = TyDyListScene.AddItem.ViewModel()
        viewController?.displayAddItem(viewModel: viewModel)
    }
    
    func presentSaveItem(response: TyDyListScene.SaveNewItem.Response) {
        let viewModel = TyDyListScene.SaveNewItem.ViewModel()
        viewController?.displaySaveItem(viewModel: viewModel)
    }
    
    func presentLoadData(response: TyDyListScene.LoadData.Response) {
        let viewModel = TyDyListScene.LoadData.ViewModel()
        viewController?.displayLoadData(viewModel: viewModel)
    }
    
    func presentUpdateData(response: TyDyListScene.UpdateData.Response) {
        let viewModel = TyDyListScene.UpdateData.ViewModel()
        viewController?.displayUpdateData(viewModel: viewModel)
    }
    
    func presentSaveData(response: TyDyListScene.SaveData.Response) {
        let viewModel = TyDyListScene.SaveData.ViewModel()
        viewController?.displaySaveData(viewModel: viewModel)
    }
    
}
