//
//  TyDyListSceneConfigurator.swift
//  TyDy
//
//  Created by Mac on 25/01/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

class TyDyListSceneConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = TyDyListSceneConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: TyDyListSceneViewController) {
        let viewController = viewController
        let interactor = TyDyListSceneInteractor()
        let presenter = TyDyListScenePresenter()
        let router = TyDyListSceneRouter()
        let worker = TyDyListSceneWorker()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.worker = worker
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
