//
//  TyDyListSceneViewController.swift
//  TyDy
//
//  Created by Mac on 25/01/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TyDyListSceneDisplayLogic: class {
    func displayAddItem(viewModel: TyDyListScene.AddItem.ViewModel)
    func displaySaveItemText(viewModel: TyDyListScene.SaveNewItem.ViewModel)
    func displayLoadData(viewModel: TyDyListScene.LoadData.ViewModel)
}

class TyDyListSceneViewController: UITableViewController {
    // MARK: Vars
    var interactor: TyDyListSceneBusinessLogic?
    var router: (NSObjectProtocol & TyDyListSceneRoutingLogic & TyDyListSceneDataPassing)?
    
    // MARK: Outlets
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        TyDyListSceneConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
          let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
          if let router = router, router.responds(to: selector) {
            router.perform(selector, with: segue)
          }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        self.loadData()
    }

    // MARK: Do something
    @IBAction func addItem(_ sender: UIBarButtonItem) {
        self.addItem()
    }
    
    func addItem() {
        let request = TyDyListScene.AddItem.Request()
        interactor?.addItem(request: request)
    }

    func saveItemText(text: String) {
        let request = TyDyListScene.SaveNewItem.Request(
            itemText: text
        )
        interactor?.saveItemText(request: request)
    }
    
    func loadData() {
        let request = TyDyListScene.LoadData.Request()
        interactor?.loadData(request: request)
    }
    
}

extension TyDyListSceneViewController: TyDyListSceneDisplayLogic {
    
    func displayAddItem(viewModel: TyDyListScene.AddItem.ViewModel) {
        let alert = UIAlertController(title: "Add new item", message: "", preferredStyle: .alert)
        let action = UIAlertAction(title: "Add Item", style: .default) { (action) in
            // here is whart will happen when user once click Add Item
            if let text = alert.textFields?.first?.text {
                self.saveItemText(text: text)
            }
        }
        alert.addTextField { (textField) in
            textField.placeholder = "Type new item here"
        }
        alert.addAction(action)
        self.present(alert, animated: true, completion: nil)
    }
    
    func displaySaveItemText(viewModel: TyDyListScene.SaveNewItem.ViewModel) {
        self.tableView.reloadData()
    }
    
    func displayLoadData(viewModel: TyDyListScene.LoadData.ViewModel) {
        self.tableView.reloadData()
    }
    
}

extension TyDyListSceneViewController {
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if let count = self.router?.dataStore?.itemArray.count {
            return count
        }
        return 0
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "tableCell", for: indexPath)
        cell.textLabel?.text = self.router?.dataStore?.itemArray[indexPath.row]
        
        return cell
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
//        print(itemArray[indexPath.row])
        let currentCell = tableView.cellForRow(at: indexPath)
        if (currentCell?.accessoryType == .checkmark ) {
            currentCell?.accessoryType = .none
        } else {
            currentCell?.accessoryType = .checkmark
        }
        tableView.deselectRow(at: indexPath, animated: true)
    }
    
}
