//
//  TyDyListSceneWorker.swift
//  TyDy
//
//  Created by Mac on 25/01/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TyDyListSceneWorker {
    
    func saveData(data: [TyDyItem]?) {
        if let data = data {
            Encoder.shared.saveData(dataToEncode: data)
        }
    }
    
    func loadData() -> [TyDyItem]? {
        return Encoder.shared.loadData()
    }
}
